---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-blue-learningtwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learningtwo-app
      version: blue
  template:
    metadata:
      name: first-blue-learningtwo-pod
      labels:
        app: learningtwo-app
        version: blue
    spec:
      containers:
      - name: learningtwo-container
        image: wahyusutejo1986/learningtwo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: learningtwo-svc
  labels:
    app: learningtwo-app
spec:
  selector:
    app: learningtwo-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 32123
    port: 80
    targetPort: 80
